# [START django_app]
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static/
- url: .*
  script: server.api.wsgi.application
  secure: always
  redirect_http_response_code: 301

env_variables:
  DJANGO_SETTINGS_MODULE: "server.settings.production"

libraries:
- name: MySQLdb
  version: 1.2.5
- name: PIL
  version: "1.1.7"
- name: ssl
  version: "2.7.11"
- name: pycrypto
  version: "2.6.1"
# [END django_app]

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^env/.*$
- ^logs/.*$
- Dockerfile
- docker-compose.yaml
- server/settings/local.py
