# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160524_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rideriders',
            name='signup_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(editable=False),
        ),
    ]
