# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 22:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160524_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2017, 6, 14), null=True),
        ),
        migrations.AlterField(
            model_name='rideriders',
            name='status',
            field=models.CharField(choices=[(b'PEN', b'Pending'), (b'ACC', b'Accepted'), (b'REG', b'Registered'), (b'REJ', b'Rejected'), (b'WIT', b'Withdrawn')], default=b'PEN', max_length=3),
        ),
    ]
