# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 09:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160614_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='mailchimp_group_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2017, 6, 19), null=True),
        ),
    ]
