# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-26 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundraisers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.Ride'),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='fundraiser',
            unique_together=set([('user', 'ride')]),
        ),
    ]
