# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-26 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(editable=False)),
                ('charge_id', models.CharField(max_length=32)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(choices=[(b'gbp', b'GBP'), (b'usd', b'USD'), (b'eur', b'EUR')], default=b'gbp', max_length=3)),
                ('livemode', models.BooleanField()),
                ('card', models.CharField(blank=True, max_length=255, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales',
            },
        ),
    ]
