# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-26 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(choices=[(b'gbp', b'GBP'), (b'usd', b'USD'), (b'eur', b'EUR')], default=b'gbp', max_length=3)),
                ('stripe_priv_key', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('stripe_pub_key', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('stripe_test_priv_key', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('stripe_test_pub_key', models.CharField(blank=True, default=b'', max_length=255, null=True)),
            ],
            options={
                'db_table': 'chapters',
            },
        ),
    ]
