# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-30 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models
import json


def migrate_payload(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    RideRiders = apps.get_model("rides", "RideRiders")
    riders = RideRiders.objects.all()
    for rider in riders:
        print rider.old_payload
        payload = json.loads(rider.old_payload)
        rider.payload = payload
        rider.save()

class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('rideriders', 'payload', 'old_payload'),
        migrations.AddField(
            model_name='rideriders',
            name='payload',
            field=django_mysql.models.JSONField(default=None),
        ),
        migrations.RunPython(migrate_payload),
        migrations.RemoveField(
            model_name='rideriders',
            name='old_payload',
        ),
    ]
