# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-20 22:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import jsonfield.fields
import server.models.sponsors


class Migration(migrations.Migration):

    replaces = [(b'server', '0001_initial'), (b'server', '0002_auto_20150529_1744'), (b'server', '0003_auto_20150529_1744'), (b'server', '0004_auto_20150609_0043'), (b'server', '0005_auto_20150708_1109'), (b'server', '0006_auto_20150716_1003'), (b'server', '0007_auto_20150818_1731'), (b'server', '0008_auto_20150818_2343'), (b'server', '0009_auto_20150908_0929'), (b'server', '0010_auto_20150908_1727'), (b'server', '0011_auto_20160524_1203'), (b'server', '0012_auto_20160524_1959'), (b'server', '0013_auto_20160614_2327'), (b'server', '0014_auto_20160619_1036'), (b'server', '0015_auto_20170505_1154'), (b'server', '0016_auto_20170505_1201'), (b'server', '0017_auto_20170913_2228')]

    initial = True

    dependencies = [
        ('auth', '0006_require_contenttypes_0002'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=b'255', unique=True)),
                ('stripe_priv_key', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('stripe_pub_key', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('stripe_test_priv_key', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('stripe_test_pub_key', models.CharField(blank=True, default=b'', max_length=255, null=True)),
            ],
            options={
                'db_table': 'chapters',
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=b'255')),
                ('slug', models.CharField(max_length=b'255', unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_location', models.CharField(max_length=b'255')),
                ('end_location', models.CharField(max_length=b'255')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('preregistration_required', models.BooleanField(default=False)),
                ('rider_capacity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('currency', models.CharField(choices=[(b'gbp', b'GBP'), (b'usd', b'USD'), (b'eur', b'EUR')], default=b'gbp', max_length=3)),
                ('terms_and_conditions', models.TextField(blank=True, default=b'', null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Chapter')),
            ],
            options={
                'db_table': 'rides',
            },
        ),
        migrations.CreateModel(
            name='RideRiders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_date', models.DateTimeField(default=datetime.datetime(2015, 5, 29, 17, 37, 31, 739772))),
                ('pending', models.BooleanField()),
                ('paid', models.BooleanField()),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Ride')),
            ],
            options={
                'db_table': 'rides_riders',
            },
        ),
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'riders_profiles',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(editable=False)),
                ('charge_id', models.CharField(max_length=32)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(choices=[(b'gbp', b'GBP'), (b'usd', b'USD'), (b'eur', b'EUR')], default=b'gbp', max_length=3)),
                ('livemode', models.BooleanField()),
                ('card', models.CharField(blank=True, max_length=255, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.AddField(
            model_name='rideriders',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Sale'),
        ),
        migrations.AddField(
            model_name='rideriders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='riders',
            field=models.ManyToManyField(blank=True, through='server.RideRiders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='rideriders',
            name='pending',
        ),
        migrations.AddField(
            model_name='rideriders',
            name='signup_expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rideriders',
            name='status',
            field=models.CharField(choices=[(b'PEN', b'Pending'), (b'ACC', b'Accepted'), (b'REG', b'Registered'), (b'REJ', b'Rejected'), (b'WIT', b'Withdrawn')], default=b'PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='rideriders',
            name='payload',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rideriders',
            name='signup_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rideriders',
            name='signup_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='rideriders',
            unique_together=set([('user', 'ride')]),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 7, 23, 43, 47, 316463, tzinfo=utc), null=True)),
            ],
            options={
                'db_table': 'memberships',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='currency',
            field=models.CharField(choices=[(b'gbp', b'GBP'), (b'usd', b'USD'), (b'eur', b'EUR')], default=b'gbp', max_length=3),
        ),
        migrations.AddField(
            model_name='chapter',
            name='membership_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='membership',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Chapter'),
        ),
        migrations.AddField(
            model_name='membership',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Sale'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapter',
            name='members',
            field=models.ManyToManyField(blank=True, through='server.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='full_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2016, 7, 7), null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='RideSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_level', models.CharField(choices=[(b'gold', b'Gold Level'), (b'silver', b'Silver Level'), (b'bronze', b'Bronze Level'), (b'bottle', b'Bottle'), (b'kit', b'Kit'), (b'inkind', b'In Kind'), (b'homecoming', b'Homecoming Party')], max_length=10)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Ride')),
            ],
            options={
                'db_table': 'ride_sponsors',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(upload_to=server.models.sponsors.generate_filename)),
                ('website', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('riders', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('rides', models.ManyToManyField(blank=True, through='server.RideSponsor', to=b'server.Ride')),
            ],
            options={
                'db_table': 'sponsors',
            },
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2016, 7, 15), null=True),
        ),
        migrations.AddField(
            model_name='ridesponsor',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Sponsor'),
        ),
        migrations.AlterUniqueTogether(
            name='ridesponsor',
            unique_together=set([('ride', 'sponsor')]),
        ),
        migrations.CreateModel(
            name='Fundraiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageId', models.IntegerField()),
                ('pageUrl', models.URLField()),
                ('signOnUrl', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fundraisers',
            },
        ),
        migrations.AddField(
            model_name='ride',
            name='fundraising_target',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ride',
            name='just_giving_event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Ride'),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='fundraisingTarget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='giftAid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='pageStatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='totalRaised',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='totalRaisedOffline',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='totalRaisedOnline',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='totalRaisedSms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='currency',
            field=models.CharField(default=b'GBP', max_length=3),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='manuallyCreated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='fundraiser',
            unique_together=set([('user', 'ride')]),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2016, 8, 17), null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2016, 9, 7), null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='strapline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2017, 5, 24), null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='end_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ride',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ride',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2017, 6, 14), null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='mailchimp_group_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2017, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2018, 5, 5), null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
