# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 11:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20150908_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='strapline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2017, 5, 24), null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='end_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ride',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ride',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 12, 3, 52, 504266)),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='organisation',
            field=models.CharField(max_length=255),
        ),
    ]
