# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 10:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20160619_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='manuallyCreated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2018, 5, 5), null=True),
        ),
    ]
