# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-26 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import server.sponsors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_level', models.CharField(choices=[(b'gold', b'Gold Level'), (b'silver', b'Silver Level'), (b'bronze', b'Bronze Level'), (b'bottle', b'Bottle'), (b'kit', b'Kit'), (b'inkind', b'In Kind'), (b'homecoming', b'Homecoming Party')], max_length=10)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.Ride')),
            ],
            options={
                'db_table': 'ride_sponsors',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(upload_to=server.sponsors.models.generate_filename)),
                ('website', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('riders', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('rides', models.ManyToManyField(blank=True, through='sponsors.RideSponsor', to='rides.Ride')),
            ],
            options={
                'db_table': 'sponsors',
            },
        ),
        migrations.AddField(
            model_name='ridesponsor',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsors.Sponsor'),
        ),
        migrations.AlterUniqueTogether(
            name='ridesponsor',
            unique_together=set([('ride', 'sponsor')]),
        ),
    ]
