import Marty from "marty";

var Constants = Marty.createConstants([
  'AUTH_USER_LOGIN',
  'AUTH_USER_LOGOUT',
  'AUTH_PASSWORD_RESET',
  'AUTH_CLEAR_ERROR',

  'RECEIVE_PARTIAL_USER',

  'RECEIVE_RIDES',

  'RECEIVE_RIDE_REGISTRATION',
  'CREATE_RIDE_REGISTRATION',
  'UPDATE_RIDE_REGISTRATION',

  'RECEIVE_RIDERS',
  'CREATE_RIDER',
  'UPDATE_RIDER',

  'RECEIVE_CHAPTERS',
  'RECEIVE_CHAPTER_MEMBERSHIP',
  'CREATE_CHAPTER_MEMBERSHIP',

  'CREATE_FUNDRAISING_PAGE',

  'RECEIVE_SPONSORS',

  'CHANGE_ROUTE'
]);

module.exports = Constants;